/* (c) 2026 LS Publication Dept. Unauthorized copying is prohibited. */
function checkPassword(){const e=document.getElementById("password").value;"lal1234"===e?(document.getElementById("passwordScreen").style.display="none",document.getElementById("mainContent").style.display="block"):alert("Incorrect VIP Password!")}function handleKeyPress(e){"Enter"===e.key&&checkPassword()}function logout(){window.location.href="https://agcneranga.github.io/LS-Publication/"}let processedRaces=[],currentDisplayMode="block";function escapeHtml(e){return e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function clearAll(){document.getElementById("raceText").value="",document.getElementById("meetingsInput").value="",document.getElementById("minPrize").value="",document.getElementById("maxPrize").value="",document.getElementById("output").innerHTML="",processedRaces=[]}function processText(e="block"){currentDisplayMode=e;const t=document.getElementById("raceText").value,n=parseInt(document.getElementById("minPrize").value||0),a=parseInt(document.getElementById("maxPrize").value||99999999),l=document.getElementById("meetingsInput").value,s=l?l.split(",").map((e=>e.trim().toUpperCase())).filter((e=>e.length>0)):[];if(!t.trim())return void alert("Please paste race card text first.");const r=t.split(/\r?\n/);let o="Unknown",c=[];const i=/^([\w]+(?:\s*\/\s*\d+)?)[\s]+(\d{1,2}[—:]\d{2})/;for(let e=0;e<r.length;e++){const t=r[e].trim();if(/^[A-Z\s\-']{1,30}$/.test(t)&&!t.match(/\d/)&&!t.includes("£")){o=t;continue}let l=t.match(i);if(l){const t=l[1].trim(),s=l[2];let u="N/A",d=0,g=[];for(let n=e+1;n<Math.min(e+12,r.length);n++){const e=r[n].trim();if("N/A"===u&&/^\(?\d{1,2}[:.]\d{2}\)?$/.test(e)){u=e.replace(/[()]/g,"");continue}if(e.includes("£")){const t=e.match(/£([\d,]+)/);t&&(d=parseInt(t[1].replace(/,/g,"")));break}e.length>2&&!/^\(?\d{1,2}[.:]\d{2}\)?$/.test(e)&&g.push(e)}s.length&&!s.includes(o.toUpperCase())||d>=n&&d<=a&&c.push({meeting:o,raceNumber:t,ukTime:s,rawSLTime:u,raceName:g.join(" "),prize:d})}}c.sort(((e,t)=>{const n=e=>{if("N/A"===e)return 9999;const t=e.split(/[:.]/).map(Number);return 60*(t[0]||0)+(t[1]||0)};return n(e.rawSLTime)-n(t.rawSLTime)})),processedRaces=c,renderRaces(c,e)}function renderRaces(e,t=currentDisplayMode){const n=document.getElementById("output");if("table"===t){let t=`<table class="vip-table"><thead><tr><th>Meeting</th><th>No.</th><th>UK Time</th><th>SL Time</th><th>Race Name</th><th>Prize (£)</th></tr></thead><tbody>`;e.forEach((e=>{t+=`<tr><td>${e.meeting}</td><td>${e.raceNumber}</td><td>${e.ukTime}</td><td>${e.rawSLTime}</td><td>${escapeHtml(e.raceName)}</td><td>${e.prize.toLocaleString()}</td></tr>`})),t+="</tbody></table>",n.innerHTML=t}else n.innerHTML=e.map((e=>`
      <div class="race-block">
        <div><strong>Race Course:</strong> ${e.meeting}</div>
        <div><strong>Race Number:</strong> ${e.raceNumber}</div>
        <div><strong>UK Time:</strong> ${e.ukTime} | <strong>SL Time:</strong> ${e.rawSLTime}</div>
        <div><strong>Race Name:</strong> ${escapeHtml(e.raceName)}</div>
        <div><strong>Prize Money:</strong> £${e.prize.toLocaleString()}</div>
      </div>
    `)).join("")}function showTopRaces(e){if(!processedRaces.length)return void alert("Please process races first.");const t=[...processedRaces].sort(((e,t)=>t.prize-e.prize)).slice(0,e);renderRaces(t)}function showBestRacePerMeeting(){if(!processedRaces.length)return void alert("Please process races first.");const e={};processedRaces.forEach((t=>{(!e[t.meeting]||t.prize>e[t.meeting].prize)&&(e[t.meeting]=t)})),renderRaces(Object.values(e).sort(((e,t)=>t.prize-e.prize)))}function downloadPDF(){if(!processedRaces.length)return void alert("No data to download.");const{jsPDF:e}=window.jspdf,t=new e;t.setFontSize(16),t.text("UK RAFFLE-ELIGIBLE RACES REPORT",14,15);const n=processedRaces.map((e=>[e.meeting,e.raceNumber,e.ukTime,e.rawSLTime,e.raceName,e.prize.toLocaleString()]));t.autoTable({head:[["Meeting","No.","UK Time","SL Time","Race Name","Prize (£)"]],body:n,startY:25,theme:"grid",headStyles:{fillColor:[67,160,71]}}),t.setFontSize(10),t.text("© 2025 | LS Publication Dept. | CN-INTERNAL",14,t.lastAutoTable.finalY+10),t.save("VIP_Race_Report.pdf")}function downloadTXT(){if(!processedRaces.length)return void alert("No data available.");let e="UK RAFFLE-ELIGIBLE RACES REPORT\n========================================\n\n";processedRaces.forEach(((t,n)=>{e+=`Race #${n+1}\nCourse: ${t.meeting}\nNo: ${t.raceNumber}\nUK: ${t.ukTime} | SL: ${t.rawSLTime}\nName: ${t.raceName}\nPrize: £${t.prize.toLocaleString()}\n----------------------------------------\n`})),e+="\n© 2025 | LS Publication Dept.";const t=new Blob([e],{type:"text/plain"}),n=document.createElement("a");n.href=URL.createObjectURL(t),n.download="Races_Report.txt",n.click()}function downloadStablesTXT(){if(!processedRaces.length)return void alert("No data available.");let e="";processedRaces.forEach((t=>{e+=`UK TIME: ${t.ukTime}\nSL TIME: ${t.rawSLTime}\nRACE COURSE: ${t.meeting}\nRACE NAME: ${t.raceName}\nPrize MONEY: £${t.prize.toLocaleString()}\n\n`})),e+="© 2025 | LS Publication Dept.";const t=new Blob([e],{type:"text/plain"}),n=document.createElement("a");n.href=URL.createObjectURL(t),n.download="Stables_Output.txt",n.click()}
// LS-CANARY-TOKEN: 7788-NERANGA-PUBLICATION-AUTH-CHECK
